VIA_ENABLE          = yes
VIAL_ENABLE         = yes

WPM_ENABLE = yes

RGBLIGHT_ENABLE     = no
RGB_MATRIX_ENABLE   = yes # Can't have RGBLIGHT and RGB_MATRIX at the same time.
MOUSEKEY_ENABLE     = yes

VIALRGB_ENABLE      = yes
CONSOLE_ENABLE = yes
EXTRAKEY_ENABLE     = yes
COMBO_ENABLE        = yes
DYNAMIC_MACRO_ENABLE = yes
BOOTMAGIC_ENABLE = yes
QMK_SETTINGS        = yes
KEY_OVERRIDE_ENABLE = yes
MAGIC_ENABLE = yes
CAPS_WORD_ENABLE = yes
LAYER_LOCK_ENABLE = no
REPEAT_KEY_ENABLE = no
TAP_DANCE_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c