OLED_ENABLE = yes
OLED_DRIVER = ssd1306
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
EXTRAKEY_ENABLE = yes
HAPTIC_ENABLE = yes
HAPTIC_DRIVER = drv2605l
DYNAMIC_MACRO_ENABLE = yes
SWAP_HANDS_ENABLE = no
COMBO_ENABLE = yes
TAP_DANCE_ENABLE = yes

AUDIO_ENABLE = yes
MUSIC_ENABLE = yes

RGB_MATRIX_ENABLE = yes

VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_ENCODERS_ENABLE = yes
VIALRGB_ENABLE = yes
VIAL_INSECURE = yes