VIA_ENABLE = yes
VIAL_ENABLE = yes

CONSOLE_ENABLE = no
LTO_ENABLE = no
QMK_SETTINGS = yes
MOUSEKEY_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes

LAYER_LOCK_ENABLE = yes
REPEAT_KEY_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes