VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = yes
VIAL_INSECURE = yes

OLED_ENABLE         = yes
EXTRAKEY_ENABLE     = yes
WPM_ENABLE = yes

LEADER_ENABLE = yes
UNICODE_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes