VIA_ENABLE = yes
VIAL_ENABLE = yes
OLED_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
WPM_ENABLE = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
GRAVE_ESC_ENABLE = yes
MAGIC_ENABLE = yes
ENCODER_MAP_ENABLE = yes
BOOTMAGIC_ENABLE = yes

RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes # Can't have RGBLIGHT and RGB_MATRIX at the same time.
VIALRGB_ENABLE = yes

COMMAND_ENABLE = yes
CONSOLE_ENABLE = no

QMK_SETTINGS = yes
LTO_ENABLE = yes

KEY_OVERRIDE_ENABLE = yes