OLED_ENABLE = yes
ENCODER_ENABLE = yes
VIA_ENABLE = yes
VIAL_ENABLE = yes
ENCODER_MAP_ENABLE = yes
<<<<<<< HEAD
=======
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
VIALRGB_ENABLE = yes
RGB_MATRIX_ENABLE = yes
>>>>>>> 775df81f659150cd49365f2eebc7fa0e6ccb3bd7
DYNAMIC_MACRO_ENABLE = yes